### ISSUE TITLE
[IMP][14.0] fieldservice_equipment_orders

### ISSUE THREAD

**Issue by marcos-mendez** [kimenz/field-service#13]
Implementar um SMART WIDGET en la vista del fsm.equipment que muestre todas las ordenes de servicio del equipamiento.

fieldservice_equipment_orders

![image](https://user-images.githubusercontent.com/38361760/208677121-04123166-5968-4337-9973-cff0f83f1201.png)

**Comment by marcos-mendez** [comment]
Puede ser al lado del smartwidget del Website

**Comment by rafnixg** [comment]
Ya se puede cerrar este Issue, se resolvio en el PR #14
