### ISSUE TITLE
[14.0] [IMP] - Fieldservice_equipment_website + Ticket History

### ISSUE THREAD

**Issue by marcos-mendez** [kimenz/field-service#4]
Add a new tab called Ticket History for the equipment.

This tab will show history of tickets

Probably this module will depend on helpdesk_mgmt

**Comment by rafnixg** [comment]
![image](https://user-images.githubusercontent.com/10915285/208202534-d6912c95-cdd6-4a6e-a801-5e06795e7042.png)

**Comment by rafnixg** [comment]
Este Issue ya fue resuelto, se trabajajo en helpdesk https://github.com/kimenz/helpdesk/pull/3 y fieldservice #12
