### ISSUE TITLE
[14.0][FIX] fieldservice_equipment_website

### ISSUE THREAD

**Issue by marcos-mendez** [kimenz/field-service#6]
CAMPOS DEBEN SER:

COLUMNA 1

NOMBRE DEL EQUIPO (fsm.equipment_name)
NUMERO DE RASTREAMENTO (lot_id)

CATEGORIA ANVISA (categ_id)(product_product)
REGISTRO ANVISA (default_code)(product_product)

COLUMNA 2
Fabricante: (brand)(product_product)
Numero de Patrimonio: (ref)

**Comment by rafnixg** [comment]
@marcos-mendez Faltaron los campos adicionales:
CE Certificate
Certificate Validity Date

en cual columna deben ir?

**Comment by marcos-mendez** [comment]
@rafnixg en la 3a columna con los botones

**Comment by rafnixg** [comment]
@marcos-mendez `CE Certificate` es un campo many2many, como mostrariamos los certificados, en una lista, o en una tabla?

**Comment by marcos-mendez** [comment]
Si en una lista
